const { TOOLS, DEPARTMENTS } = require('../lib/config');

/**
 * Generate README.md content for the generated configuration
 * @param {Object} config - Configuration object
 * @param {Object} result - Generation result
 * @returns {string} README content
 */
function generateReadme(config, result) {
  const tool = TOOLS[config.tool];
  const timestamp = new Date().toISOString();

  return `# AI Agents Configuration

> Generated with [AgentKit](https://github.com/patricio0312rev/agentkit) 🤖

## 📋 Overview

- **Tool**: ${tool.name}
- **Location**: \`${config.folder}/\`
- **Departments**: ${config.departments.length}
- **Agents**: ${result.agentsGenerated}
- **Generated**: ${new Date().toLocaleString()}

## 🚀 Usage

${getDetailedUsageInstructions(config.tool)}

## 📁 Structure

\`\`\`
${config.folder}/
${generateStructureTree(config)}
\`\`\`

## 🏢 Departments Included

${generateDepartmentsList(config)}

${config.stack.length > 0 ? generateStackSection(config.stack) : ''}

## 🔄 Updating

To regenerate or update your configuration:

\`\`\`bash
npx agentkit init
\`\`\`

Or if installed globally:

\`\`\`bash
agentkit init
\`\`\`

## 📚 Resources

- [AgentKit Documentation](https://github.com/patricio0312rev/agentkit)
- [Claude Code Documentation](https://code.claude.com/docs)
- [Cursor Documentation](https://cursor.sh/docs)

## 💡 Tips

- Commit these files to version control
- Share with your team for consistent AI assistance
- Update regularly as your project evolves
- Customize agent instructions for your specific needs

---

*Generated by AgentKit v${require('../../package.json').version}*
`;
}

function getDetailedUsageInstructions(tool) {
  const instructions = {
    'claude-code': `### With Claude Code CLI

The agents in this folder are automatically loaded by Claude Code.

\`\`\`bash
# Use agents in your prompts naturally
claude-code "Build a login page using the frontend-developer patterns"

# Reference specific agents
claude-code "Review this API design with the backend-architect agent"
\`\`\`

### Sub-Agent System

Claude Code's sub-agent system allows multiple specialized agents to work together on complex tasks.`,

    'cursor': `### With Cursor

**Method 1: @-mentions**

\`\`\`
In Cursor chat, use @-mentions:
@engineering/backend-architect.md Design a REST API for user management
\`\`\`

**Method 2: Natural References**

Just reference the agent naturally in your prompts:
\`\`\`
"Using the backend-architect guidelines, design an API..."
\`\`\`

### Settings

1. Cursor automatically detects agent files in common folders
2. You can also configure custom folders in Cursor settings`,

    'copilot': `### With GitHub Copilot

The configuration file is located at:
\`\`\`
.github/copilot-instructions.md
\`\`\`

GitHub Copilot will automatically use these instructions when:
- Writing code
- Suggesting completions
- Answering questions in chat

No additional setup required!`,

    'universal': `### With Any AI Tool

1. **Upload Method**: Upload relevant agent .md files to your AI chat
2. **Reference**: Reference them in your prompts
3. **Copy-Paste**: Or copy agent content directly into context

Example:
\`\`\`
[Upload: engineering/backend-architect.md]

"Following the backend-architect guidelines, help me design..."
\`\`\``
  };

  return instructions[tool] || instructions.universal;
}

function generateStructureTree(config) {
  const lines = ['├── README.md'];
  
  config.departments.forEach((dept, index) => {
    const isLast = index === config.departments.length - 1;
    const prefix = isLast ? '└──' : '├──';
    lines.push(`${prefix} ${dept}/`);
    
    const agents = DEPARTMENTS[dept].agents;
    agents.forEach((agent, agentIndex) => {
      const agentIsLast = agentIndex === agents.length - 1;
      const agentPrefix = isLast ? '    ' : '│   ';
      const agentMarker = agentIsLast ? '└──' : '├──';
      lines.push(`${agentPrefix}${agentMarker} ${agent}.md`);
    });
  });

  return lines.join('\n');
}

function generateDepartmentsList(config) {
  return config.departments.map(dept => {
    const deptInfo = DEPARTMENTS[dept];
    return `### ${deptInfo.name}

${deptInfo.description}

**Agents** (${deptInfo.agents.length}):
${deptInfo.agents.map(agent => `- \`${agent}\``).join('\n')}
`;
  }).join('\n');
}

function generateStackSection(stack) {
  return `## 🛠️ Tech Stack

This configuration is optimized for:

${stack.map(tech => `- ${tech}`).join('\n')}

Agents are aware of this stack and will provide relevant guidance.
`;
}

module.exports = {
  generateReadme
};
